# Generated by Django 5.2.16 on 2026-07-30 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('products', '0002_alter_product_image_principale'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='products.product'),
        ),
    ]
