# Generated by Django 5.2.16 on 2026-07-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
