# Generated by Django 5.2.16 on 2026-07-30 02:53

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_principale',
            field=models.ImageField(blank=True, null=True, upload_to='products/', validators=[products.models.validate_image_extension]),
        ),
    ]
