# Generated by Django 5.2.16 on 2026-07-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image_principale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vues_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
