# Generated by Django 5.2.16 on 2026-07-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_image_fields_to_textfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nom',
            field=models.CharField(max_length=255),
        ),
    ]
